// Copyright (C) RedCraft86. All Rights Reserved.

#pragma once

#include "Helpers/GameplayTagMacros.h"

namespace PlayerLockTag
{
	TOROUTILITIES_API DECLARE_GAMEPLAY_TAG(PlayerLock)
    TOROUTILITIES_API DECLARE_GAMEPLAY_TAG(MainMenu)
    TOROUTILITIES_API DECLARE_GAMEPLAY_TAG(Startup)
    TOROUTILITIES_API DECLARE_GAMEPLAY_TAG(Loading)
	TOROUTILITIES_API DECLARE_GAMEPLAY_TAG(Dialogue)
	TOROUTILITIES_API DECLARE_GAMEPLAY_TAG(Cinematic)
	TOROUTILITIES_API DECLARE_GAMEPLAY_TAG(GameOver)

	TOROUTILITIES_API CREATE_TAG_VERIFIER(PlayerLock)
}
